### ISSUE TITLE
Error: undefined is not an object (evaluating 'attr.split')

### ISSUE THREAD

**Issue by LarsG** [AdamBuczynski/ngGo#25]
Hi Adam, I tried to get ngGo working in a AngularJS MVC structure and I get the Error: undefined is not an object (evaluating 'attr.split') at line lib/ngGo/ngGo.js:231:31. I use the $route service and and render a  template with the board tag in index.html with <section ng-view></section>

**Comment by AdamBuczynski** [comment]
@LarsG thanks, I will look into it. Did you mean to write something else? Your last sentence seems unfinished.

**Comment by AdamBuczynski** [comment]
Should be fixed! (In the dev branch).

**Comment by LarsG** [comment]
Hi Adams, thanks for the fast answer and sorry for the messed up last sentence. After I rebuild my app structure I couldn't reproduce the error anymore which is quite strange. 

However, for the other bug I found I made a small fix and pull request.

**Comment by AdamBuczynski** [comment]
No worries, glad to help.
