### ISSUE TITLE
File type detection does not always work

### ISSUE THREAD

**Issue by horaceho** [adambuczynski/ngGo#29]
In `Game.prototype.fromData`, file type is determined by the first char in data. For example, the first char of the bundled `test.jgf` file is not a `'{'`.

**Comment by adambuczynski** [comment]
Hi, the test.jgf file actually only contains the tree of the moves. The actual JGF file format should start with a `{` symbol, as it will be an object containing a variety of other properties as well.

See https://github.com/adambuczynski/ngGo/blob/master/JGF.md for the specification.

I think the `test.jgf` file may be outdated, I will look into it.

**Comment by adambuczynski** [comment]
I will include parsing of an array as JGF, and assume it's a JGF tree of moves.

**Comment by adambuczynski** [comment]
Added in 1.2.0

**Comment by horaceho** [comment]
Thank you!
