### ISSUE TITLE
Demos do not run in 1.2.2

### ISSUE THREAD

**Issue by horaceho** [adambuczynski/ngGo#31]
After downloading the whole project as a .zip from GitHub, the .html files in demo folder do not run in 1.2.2 (angular missing?). It was OK in 1.1.

Besides, there are two ngGo.js files (one in root, one in release folder).

**Comment by adambuczynski** [comment]
Yes please check the release notes for 1.2. I have deferred Angular to be installed via npm, so you can do `npm install` in the package folder to get Angular. Or you can change the demo html files to point to your own Angular install.

The ngGo file in the root is not right. I'll remove it, thanks for letting me know.
