### ISSUE TITLE
Is there an option to show move number on top of stones?

### ISSUE THREAD

**Issue by horaceho** [adambuczynski/ngGo#34]
![move_numbers](https://cloud.githubusercontent.com/assets/6657/13947235/3c05b5dc-f054-11e5-9ad7-812b8033e17b.png)

... similar to the about diagram. It'll be great if ngGo will support:
````
  Player.showMoveNumbers(); // show number for all stones
  Player.showMoveNumbers(fromMove, toMove); // for a range of moves
  Player.showMoveNumbersFromLastComment(); // from previous comment to current move
````

**Comment by adambuczynski** [comment]
I like how you used an AlphaGo game :)
I will look into this after my holiday.

**Comment by adambuczynski** [comment]
@horaceho It appears that this is already implemented.

There exists a method `Player.showMoveNumbers(fromMove, toMove)`
Defaults to all moves, if no parameters given.

There is no support for showing move numbers from the last comment. 
You will have to manually loop the nodes and find the last comment (or remember it) and then supply that value as fromMove.

Let me know if you have further questions. This functionality is also testable in the demo.
