### ISSUE TITLE
I need a help. It's not running for me. I am using an example in the Wiki section.

### ISSUE THREAD

**Issue by cosmir17** [adambuczynski/ngGo#38]
Hello :)

I created a simple angularjs project to use your library.
I am using an example in the wiki section.
https://github.com/adamreisnz/ngGo/wiki/Quickstart

I have 'index.html'. I don't need more than a page. 
https://github.com/cosmir17/go-ai-client-angularjs/blob/master/app/index.html

For some reason, nothing is loaded on the page.
<img width="1490" alt="screenshot 2019-02-23 at 16 12 46" src="https://user-images.githubusercontent.com/2845708/53288866-fe694280-3785-11e9-9cd4-e726481b5388.png">

ng-go library seems running inside 'app.js' as you can see a console log on the screenshot.
https://github.com/cosmir17/go-ai-client-angularjs/blob/master/app/app.js
However, I am not seeing anything on my browser.

Can I know what mistake I made?

Thank you,
cosmir17

**Comment by cosmir17** [comment]
`<board coordinates="true" size="9x9" cutoff="top,left" instance="Board"></board>`
If I have 'size' attribute in index.html, it would work. However, it won't work by just having it in .js file. (e.g. ...new Board({width: 9, height: 9}...)

**Comment by adamreisnz** [comment]
Hi there, thanks for raising an issue, I'm glad you figured out how to resolve it.

I haven't looked into this library for a few years, so I can't remember how you're supposed to run it I'm afraid. It would be nice to work on this again, but unfortunately I don't have the time at the moment.

Good luck with your project though, let me know if you run into any other issues!

**Comment by cosmir17** [comment]
Thank you, Adam.
I am just glad that there is a FE library that I can use. Otherwise, I may do only backend work (I am a backend, a scala developer)
I happen to have another question.
I shall post one, once I draw a diagram.
Wish you a good day :)
