### ISSUE TITLE
I need a help. I want FE & BE to engage in the same game play

### ISSUE THREAD

**Issue by cosmir17** [adambuczynski/ngGo#39]
Hello,

![img_3681](https://user-images.githubusercontent.com/2845708/53327950-d2ae9f80-38e0-11e9-9273-221a6d56ab88.JPG)

There are many examples(modes) on the wiki page but I couldn't find one that suits my need.

1. How can I have player 1 (user input)

```
Player.on("click", function(event, mouseEvent) {
    console.log("Clicked on grid coordinates:", event.x, event.y);
});
```

This just prints the coordinates on the console. How can I play a game?

2. How can I set up player 2 (backend), I can work on the http part.
3. How can I make player 1 & 2 to play together?
The following line seems setting up a game but I want to have a game for two players.
`$scope.Game = Player.game;`

My current project is :
https://github.com/cosmir17/go-ai-client-angularjs/blob/master/app/index.html
https://github.com/cosmir17/go-ai-client-angularjs/blob/master/app/app.js

Please let me know if I have to change something in my code as well not only your guidance.

Thank you,
cosmir17

**Comment by adamreisnz** [comment]
Hi cosmir, thanks for your question, however this library does not support playing a full game out of the box. You'll have to actually develop the game playing mechanics yourself in your app, as well as any http connection.

We had a project that we wanted to work on a while ago which would have done something similar. However, unfortunately it was cancelled and never got built.

I recommend just looking through the code and examples and finding the available parts and see how you can use them. The API is very flexible and you can place stones and make moves quite easily. You just need a script around it to control all that.

Look in particular at the game service and the play method: https://github.com/adamreisnz/ngGo/blob/master/src/game/game.service.js#L1142

**Comment by cosmir17** [comment]
Hi Adam,

Thank you for the advice with an example. I am just happy that there is a javascript library.
Wish you a good day.

Thank you,
Cosmir17
